# Generated by Django 3.2 on 2021-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('published', 'Опубликован'), ('on moderation', 'На модерации'), ('rejected', 'Отклонен')], default='on moderation', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
