# Generated by Django 3.2 on 2021-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес в граммах')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в рублях')),
            ],
        ),
    ]
